### ISSUE TITLE
right-to-left languages

### ISSUE THREAD

**Issue by Theamoz** [MaKTaiL/gemini-srt-translator#2]
Everything is working well, but I was wondering if you could address the issue of right-to-left languages, such as Arabic and Persian

**Comment by MaKTaiL** [comment]
Could you provide me an example? What is the issue?

**Comment by Theamoz** [comment]
![{3D1E2624-4ABD-452C-BE18-9E3F717D8887}](https://github.com/user-attachments/assets/e47f5016-5473-4368-97c9-0d0fcb38814d)
For example, all symbols instead of the end of the line go to the beginning of the line.
![{6481AE02-FF22-4A19-A417-CABB35C67FCC}](https://github.com/user-attachments/assets/2e6fc41c-c333-4475-835a-c91fb3eda478)
And in this example, where an English word was added to the text, the entire sentence became scrambled and ruined.

I think this might help
https://stackoverflow.com/questions/69424382/fixing-rtl-texts-from-logical-to-visual-before-embedding-in-video-as-subtitle

**Comment by Theamoz** [comment]
```
import pysrt
from collections import Counter
import unicodedata as ud

def dominant_strong_direction(s):
    count = Counter([ud.bidirectional(c) for c in list(s)])
    rtl_count = count['R'] + count['AL'] + count['RLE'] + count["RLI"]
    ltr_count = count['L'] + count['LRE'] + count["LRI"]
    return "rtl" if rtl_count > ltr_count else "ltr"

def convert_srt_to_rtl(input_file, output_file):
    subs = pysrt.open(input_file)
    for sub in subs:
        if dominant_strong_direction(sub.text) == "rtl":
            sub.text = "\u202b" + sub.text + "\u202c"
    subs.save(output_file, encoding='utf-8')

if __name__ == "__main__":
    input_file = "subtitle.srt"
    output_file = "subtitle_rtl.srt"
    convert_srt_to_rtl(input_file, output_file)
```
Hey, brother, I've written this and it works really well. Please try to incorporate it into the project. For instance, if the target language is Persian, we can use it to ensure the subtitles are generated correctly.

**Comment by MaKTaiL** [comment]
Hi, I'll see what I can do and I'll let you know ;)

**Comment by MaKTaiL** [comment]
@Theamoz can you provide a .srt file and a target language for me to test?

**Comment by Theamoz** [comment]
> I've done some changes here. @Theamoz can you provide a .srt file and a target language for me to test? I'll translate and give it back to you so you can check if it worked.
sure
The first file, named 'en', has not been translated yet and the target language is Persian The second file, named 'fa', has been translated and the RTL issue has been resolved .
The final output should match the 'fa' file.

**Comment by MaKTaiL** [comment]
Ok, just did a translation. Can you check the result? 
[001 fa2 test.zip](https://github.com/user-attachments/files/17492175/001.fa2.test.zip)

**Comment by Theamoz** [comment]
it's perfect.
