### ISSUE TITLE
Better translation

### ISSUE THREAD

**Issue by Theamoz** [MaKTaiL/gemini-srt-translator#7]
The ability to tell Gemini what a subtitle is about can be very useful. For example, for a subtitle from a programming tutorial, it would be helpful to tell Gemini not to translate certain keywords used in that language.
What I mean is, it would be a great feature if we could tell Gemini what a subtitle is about so it can understand that certain words should be kept in their original language.
I think this would be most useful for educational courses.

**Comment by Theamoz** [comment]
[gemini_srt_translator.zip](https://github.com/user-attachments/files/17508380/gemini_srt_translator.zip)
Hey man, I made some changes and it's working well

**Comment by MaKTaiL** [comment]
Hi, your suggestion is in the pipeline for next update.

**Comment by MaKTaiL** [comment]
Feature implemented on version 1.2.5.
