### ISSUE TITLE
It stopped working at around 900 lines and it started to loop "quota exceeded, waiting 1 minute" forever

### ISSUE THREAD

**Issue by mrklhsnbrg** [MaKTaiL/gemini-srt-translator#8]
I tested the model gemini-1.5-flash-002 for my target language. It was fast but the result wasn't very good. So I switched to the Pro model instead with the following configuration. 

gst.model_name = "gemini-1.5-pro-002"
gst.batch_size = 50

gst.translate()

If I understand correctly, batch size of 50 will make around 18 requests, which is far less than the 50 requests per day.
![image](https://github.com/user-attachments/assets/db56a1f5-d892-48e5-9b51-035d69951d1f)

But the code start to loop at 900/1586 lines. Any idea why is this? Is there a way for the code to tell me when I am running out of API in a day. Thank you

> Starting translation of 1586 lines...
> Translated 50/1586
> Translated 100/1586
> Translated 150/1586
> Translated 200/1586
> Quota exceeded, waiting 1 minute...
> Translated 250/1586
> Translated 300/1586
> Quota exceeded, waiting 1 minute...
> Translated 350/1586
> Quota exceeded, waiting 1 minute...
> Translated 400/1586
> Quota exceeded, waiting 1 minute...
> Translated 450/1586
> Quota exceeded, waiting 1 minute...
> Translated 500/1586
> Quota exceeded, waiting 1 minute...
> Translated 550/1586
> Quota exceeded, waiting 1 minute...
> Translated 600/1586
> Quota exceeded, waiting 1 minute...
> Translated 650/1586
> Quota exceeded, waiting 1 minute...
> Translated 700/1586
> Quota exceeded, waiting 1 minute...
> Translated 750/1586
> Quota exceeded, waiting 1 minute...
> Translated 800/1586
> Quota exceeded, waiting 1 minute...
> Translated 850/1586
> Quota exceeded, waiting 1 minute...
> Translated 900/1586
> Quota exceeded, waiting 1 minute...
> Quota exceeded, waiting 1 minute...
> Quota exceeded, waiting 1 minute...
> Quota exceeded, waiting 1 minute...
> Quota exceeded, waiting 1 minute...

**Comment by MaKTaiL** [comment]
Pro has a free limit of 2 requests per minute. I'm not sure why it suddenly starts looping at the end there though. I haven't really tried Pro on my side. Can you try version 001? Are you using the latest version of gemini-srt-translator?

**Comment by MaKTaiL** [comment]
Tomorrow I'll try patching this. I'll add a 30s cooldown between requests when using the free pro version. This should solve the issue albeit at the cost of speed.
